name: reminder
description: "A new Flutter project."
version: 1.0.0+1


environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter

  awesome_notifications_core: any
  awesome_notifications: any
  freezed_annotation: ^2.4.4
  flutter_timezone: ^2.1.0
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  injectable: ^2.4.1
  timezone: ^0.9.4
  sqflite: ^2.3.3+1
  get_it: ^7.7.0
  path: ^1.9.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  freezed: ^2.5.7


flutter:
  generate: true
  uses-material-design: true